theme: jekyll-theme-cayman
title: Team Bitconnect Homepage
description: Homepage for Team Bitconnect's term project in HCI.

github:
  homepage_url: https://nathanwynn.github.io/HCI-homepage/
  milestone2_url: https://nathanwynn.github.io/HCI-homepage/Milestone_2.html
  milestone3_url: https://nathanwynn.github.io/HCI-homepage/Milestone_3.html
  milestone4_url: https://nathanwynn.github.io/HCI-homepage/Milestone_4.html